### ISSUE TITLE
Missing Text info (like text size and text Font info)

### ISSUE THREAD

**Issue by Ribosome2** [PsdPlugin/PsdPlugin#12] opened 2020-11-09 06:18 UTC
Hi,how do I  get text info  from .psd file ,I try to  decode more info refrencing this page ,https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577411_21585, but there is no ‘tySh’ in layers, only the 'TySh'  'supersedes the type tool info in Photoshop 5.0' but I cannot get text info in 'TySh' layer info ,I wonder if you had done it ? Any help is appriciatied !

**Comment by taoyue** [comment] 2020-11-10 03:21
Closing as Not a Bug.  Because Paint.NET does not have text layers, this is out-of-scope for the PSD Plugin.

Go to the URL you gave, and click on "See Type tool object setting (Photoshop 6.0)."  Then click on "See Descriptor Structure."  Much of the PSD file format is undocumented, so it may not have everything that you need.  However, it contains the overall TySh structure.

**Closed by taoyue** 2020-11-10 03:21 UTC
